#!/usr/bin/env bash
# Shortened solution to Webstack Debugging #1 challenge
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx start
kill $(pgrep 'nginx' | head -1)
