#!/usr/bin/env bash
# This script will loop from 1 to 20 and display different messages depending on the iteration

count=1
while [ $count -le 20 ]; do
    echo $count
    case $count in
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac
    count=$((count+1))

    case $count in
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
        *) echo "Best school";;
    esac
done
